### ISSUE TITLE
ImportError: cannot import name _args_from_interpreter_flags

### ISSUE THREAD

**Issue by isbadawi** [jarus/flask-testing#39]
I have a flask app which uses `multiprocessing` when computing stuff. When I add `import flask.ext.testing` at the top of my test module (and nothing else, not using it yet), I get this when I run my tests:

```
Traceback (most recent call last):
  File "mcbench_tests.py", line 5, in <module>
    import app
  File "/Users/isbadawi/code/py/mcbench/app.py", line 5, in <module>
    import mcbench.client
  File "/Users/isbadawi/code/py/mcbench/mcbench/client.py", line 4, in <module>
    from mcbench.benchmark import Benchmark, BenchmarkSet
  File "/Users/isbadawi/code/py/mcbench/mcbench/benchmark.py", line 5, in <module>
    import multiprocessing
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.py", line 40, in <module>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name _args_from_interpreter_flags
```

**Comment by srossross** [comment]
This fixes the issue for me:

```
pip install Flask-Testing --upgrade
pip uninstall twill
```
