### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'terminate'

### ISSUE THREAD

**Issue by rafaelreuber** [jarus/flask-testing#79]
I'm getting the error below when I use to flask.ext.testing.LiveServerTestCase class with python 3.3

```python
Traceback (most recent call last):
  File "C:\Users\Reuber\env_stormy_flask\lib\site-packages\flask_testing\utils.py", line 345, in __call__
    self._spawn_live_server()
  File "C:\Users\Reuber\env_stormy_flask\lib\site-packages\flask_testing\utils.py", line 366, in _spawn_live_server
    self._process.start()
  File "C:\Python33\Lib\multiprocessing\process.py", line 111, in start
    self._popen = Popen(self)
  File "C:\Python33\Lib\multiprocessing\forking.py", line 248, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python33\Lib\multiprocessing\forking.py", line 166, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class '_thread.lock'>: attribute lookup _thread.lock failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\Lib\runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python33\Lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "C:\Python33\Lib\unittest\__main__.py", line 19, in <module>
    main(module=None)
  File "C:\Python33\Lib\unittest\main.py", line 125, in __init__
    self.runTests()
  File "C:\Python33\Lib\unittest\main.py", line 265, in runTests
    self.result = testRunner.run(self.test)
  File "C:\Python33\Lib\unittest\runner.py", line 168, in run
    test(result)
  File "C:\Python33\Lib\unittest\suite.py", line 67, in __call__
    return self.run(*args, **kwds)
  File "C:\Python33\Lib\unittest\suite.py", line 105, in run
    test(result)
  File "C:\Python33\Lib\unittest\suite.py", line 67, in __call__
    return self.run(*args, **kwds)
  File "C:\Python33\Lib\unittest\suite.py", line 105, in run
    test(result)
  File "C:\Python33\Lib\unittest\suite.py", line 67, in __call__
    return self.run(*args, **kwds)
  File "C:\Python33\Lib\unittest\suite.py", line 105, in run
    test(result)
  File "C:\Users\Reuber\env_stormy_flask\lib\site-packages\flask_testing\utils.py", line 348, in __call__
    self._terminate_live_server()
  File "C:\Users\Reuber\env_stormy_flask\lib\site-packages\flask_testing\utils.py", line 373, in _terminate_live_server
    self._process.terminate()
  File "C:\Python33\Lib\multiprocessing\process.py", line 119, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Comment by robertlagrant** [comment]
Yep - I get the same error.

**Comment by greyli** [comment]
Same issue on Windows7 with Python 2.7.

**Comment by ProLoDs** [comment]
Still an issue with Windos 10 in 2018

**Comment by jamiebull1** [comment]
Same for Windows 10 in 2019

**Comment by RamNewton** [comment]
Same for Windows 10 in 2020. Are we missing something here?

**Comment by NRGunby** [comment]
I've also been getting this (Windows 10, Python 3.7).

I've done some investigation and the root of the problem is that multiprocessing works differently on unix and windows.

On unix, fork() is available, where the OS copies everything for you automatically.

On windows, it is not, and we have to use spawn() instead, which requires the use of pickle to copy variables to the child process. One of the limitations on pickle is that it can copy only copy functions defined at the top level.

The worker that is being spawned is a multiply-nested function ( utils.py -> LiveServerTestCase -> _spawn_live_server() -> worker() -> socket_bind_wrapper() ) so can't be pickled, so we can't start a new thread on windows.

I tried extracting socket_bind_wrapper() and worker() out to the top level of the module, and it fixed this error, but instead of the test working I got the error

`AttributeError: Can't pickle local object 'SQLAlchemy.init_app.<locals>.shutdown_session'`

I'm not sure if this is just a problem with my application's architecture (I'm not that experienced with flask), or if it's intrinsic to flask.

**Comment by kennell** [comment]
2022, still there

sys

```
macOS 11.4
Python 3.9.9
```

versions

```
Flask==2.0.2
Flask-Testing==0.8.1
```

**Comment by changchiyou** [comment]
Got the same error with 

```
macOS Sonoma 14.0
Python 3.10.11
flask 3.0.0
flask-testing 0.8.1
```

According to https://github.com/jarus/flask-testing/issues/79#issuecomment-696666072 and [ChatGPT](https://chat.openai.com/share/ec1272e2-6276-4e57-9e8b-4098b982e5de), here is the workaround **for macOS**:

https://github.com/jarus/flask-testing/blob/5107691011fa891835c01547e73e991c484fa07f/flask_testing/utils.py#L487

```
-  self._process = multiprocessing.Process(
+  self._process = multiprocessing.get_context("fork").Process(
```
