### ISSUE TITLE
RuntimeError since 0.6.0

### ISSUE THREAD

**Issue by ziirish** [jarus/flask-testing#91]
Hi,

Since 0.6.0 I can't get my tests succeed anymore. They all fail with the following error:

```
======================================================================
ERROR: test_live_monitor (test_burpui.BurpuiRoutesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/burp-ui/py/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/tmp/burp-ui/py/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/tmp/burp-ui/py/lib/python2.7/site-packages/flask_testing/utils.py", line 112, in __call__
    self._post_teardown()
  File "/tmp/burp-ui/py/lib/python2.7/site-packages/flask_testing/utils.py", line 170, in _post_teardown
    message_flashed.disconnect(self._add_flash_message)
  File "/tmp/burp-ui/py/lib/python2.7/site-packages/flask/signals.py", line 32, in _fail
    raise RuntimeError('signalling support is unavailable '
RuntimeError: signalling support is unavailable because the blinker library is not installed.
```

- nose-1.3.7
- Flask-Testing-0.6.0
- Flask-0.11.1

**Comment by jcomo** [comment]
My apologies -- our test matrix doesn't currently support having and not having additional libraries (like blinker) installed. There was a bug introduced that did not check for signal support before connecting/disconnecting in setup and teardown methods and none of the automated tests caught since blinker is always installed in the test environment. I will make a follow up task to improve that capability so we don't regress like this in the future. In the meantime, please update to 0.6.1 where the issue has been fixed :)

**Comment by ziirish** [comment]
No problem,
Thanks for the quick feedback and fix!

Keep up the good work.
